Moves directory

diff --git a/.github/workflows/maestro-tests.yaml b/.github/workflows/maestro-tests.yaml
--- a/.github/workflows/maestro-tests.yaml
+++ b/.github/workflows/maestro-tests.yaml
@@ -40,7 +40,11 @@ jobs:
           unzip commandlinetools.zip
           rm commandlinetools.zip
           mkdir -p $ANDROID_HOME/cmdline-tools/latest
-          mv cmdline-tools latest
+          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
+          if [ ! -f "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
+            echo "sdkmanager not found"
+            exit 1
+          fi
 
       - name: Accept SDK Licenses
         run: |
