Moves maestro tests into main action file.

diff --git a/.github/workflows/maestro-tests.yaml b/.github/workflows/maestro-tests.yaml
--- a/.github/workflows/maestro-tests.yaml
+++ b/.github/workflows/maestro-tests.yaml
@@ -99,17 +99,46 @@ jobs:
             echo "Waiting for the emulator to boot up..."
             adb wait-for-device
             until adb shell getprop sys.boot_completed | grep -m 1 '1'; do echo "Waiting for device to boot..."; sleep 10; done
+
             echo "Device booted. Listing connected devices:"
             adb devices
             adb shell input keyevent 82
+
             echo "Disabling animations..."
             adb shell settings put global window_animation_scale 0.0
             adb shell settings put global transition_animation_scale 0.0
             adb shell settings put global animator_duration_scale 0.0
+
             echo "Installing the APK..."
             adb install ${{ env.APK_PATH }} || (adb kill-server && adb start-server && adb devices && adb install ${{ env.APK_PATH }})
+
             echo "Running Maestro tests..."
-            ./run_android_e2e.sh
+            set -x
+            TMP_FILE=_fail_proccess
+            $ANDROID_HOME/platform-tools/adb shell screenrecord /sdcard/video_record.mp4 & echo $! > video_record.pid
+            sleep 3
+            APP_ID=com.comapeo.tests
+            (echo "===== Run E2E Attempt:  1 ====" &&             $HOME/.maestro/bin/maestro test e2e --env=APP_ID="$APP_ID" --format=junit --output report1.xml) || \
+            (echo "===== Run E2E Attempt:  2 ====" && sleep 20 && $HOME/.maestro/bin/maestro test e2e --env=APP_ID="$APP_ID" --format=junit --output report2.xml) || \
+            (echo "===== Run E2E Attempt:  3 ====" && sleep 60 && $HOME/.maestro/bin/maestro test e2e --env=APP_ID="$APP_ID" --format=junit --output report3.xml) || \
+            (echo "===== Run E2E Step Failed ====" && touch "$TMP_FILE")
+            kill -SIGINT "$(cat video_record.pid)"
+            sleep 3
+            rm -rf video_record.pid
+            $ANDROID_HOME/platform-tools/adb shell screencap -p /sdcard/last_img.png
+            $ANDROID_HOME/platform-tools/adb pull /sdcard/last_img.png
+            $ANDROID_HOME/platform-tools/adb pull /sdcard/video_record.mp4
+            $ANDROID_HOME/platform-tools/adb shell rm /sdcard/video_record.mp4
+            echo "::group::Maestro hierarchy"
+            $HOME/.maestro/bin/maestro hierarchy
+            echo "::endgroup::"
+            if [ -f "$TMP_FILE" ]; then
+              rm -rf "$TMP_FILE"
+              echo "3 tries have failed..."
+              exit 1
+            else
+              echo "Success..."
+            fi
 
       - name: List Maestro Test Results Directory
         run: ls -la $HOME/.maestro/tests/
