Checks for kvm support. Some diagnostics.

diff --git a/.github/workflows/maestro-tests.yaml b/.github/workflows/maestro-tests.yaml
--- a/.github/workflows/maestro-tests.yaml
+++ b/.github/workflows/maestro-tests.yaml
@@ -86,24 +86,37 @@ jobs:
           name: apk
           path: ./
 
+      - name: Check for KVM support
+        run: |
+          egrep -c '(vmx|svm)' /proc/cpuinfo || echo "No hardware virtualization support"
+          dmesg | grep -i kvm || echo "No KVM support in dmesg"
+
       - name: Install KVM and dependencies
         run: |
+          sudo apt-get update
           sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
           sudo adduser $(whoami) kvm
           sudo adduser $(whoami) libvirt
-          sudo modprobe kvm
+          sudo modprobe kvm || echo "KVM module not found"
 
       - name: Verify KVM Installation
         run: |
-          ls -l /dev/kvm
-          dmesg | grep -i kvm
+          if [ ! -e /dev/kvm ]; then
+            echo "KVM device not found, printing additional diagnostics"
+            uname -r
+            lsmod | grep kvm || echo "KVM module not loaded"
+            dmesg | grep -i kvm
+            exit 1
+          else
+            echo "KVM is available"
+            ls -l /dev/kvm
+          fi
 
       - name: Enable KVM
         run: |
           echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
           sudo udevadm control --reload-rules
           sudo udevadm trigger --name-match=kvm
-          ls /dev/kvm
 
       - name: Clean up space
         run: |
